<?php
/**
 * @file
 * Code for the Gent2014 - User Register feature.
 */

include_once 'gent2014_user_register.features.inc';

/**
 * Implements hook_form_alter().
 *
 * Sets the og_user_node field access to FALSE.
 * This field automatically makes the user who registered,
 * a member of the (DrupalCamp) event.
 *
 * @param array $form
 *   Form structure.
 * @param array $form_state
 *   Form state array.
 * @param String $form_id
 *   String identifier of the form.
 */
function gent2014_user_register_form_alter(&$form, &$form_state, $form_id) {
	if ($form_id !== 'user_register_form' && $form_id !== 'user_profile_form') {
		return;
	}
  drupal_set_title(t('Register'));
	$form['og_user_node']['#access'] = FALSE;
  $form['actions']['submit']['#value'] = t('Register for DrupalCamp');
}

/**
 * Implements hook_block_info().
 */
function gent2014_user_register_block_info() {
  // This example comes from node.module.
  /*
   *$blocks['syndicate'] = array(
   *  'info' => t('Syndicate'),
   *  'cache' => DRUPAL_NO_CACHE
   *);
   */
  $blocks['community_register_link'] = array(
    'info' => t('Join the community link'),
    'cache' => DRUPAL_CACHE_GLOBAL
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function gent2014_user_register_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'community_register_link':
      $block['subject'] = '';
      $block['content'] = theme('html_tag', array(
      'element' => array(
        '#tag'        => 'p',
        '#value'      => l(t('Register'), 'user/register'),
        '#attributes' => array('class' => drupal_html_class('cta-button')),
      )
    ));
    break;
  }

  return $block;
}
