<?php
/**
 * @file
 * General drupalcamp fixes
 */

/**
 * Implements hook_menu_alter().
 */
function drupalcamp_menu_alter(&$items) {
  $items['user/register']['title'] = 'Register';
  $items['user/register']['weight'] = 20;
  $items['user/%user/tickets']['access callback'] = FALSE;
  $items['user/%user/sessions']['access callback'] = FALSE;
  $items['user/%user/edit']['title'] = t('Edit Your Details');
}

